[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_news = "3DZZTzzjsZurjncMYe6B4DZ35SnxHbUC8TdQkQ7EHYUL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/vladyslavkramarenko/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
